### ISSUE TITLE
wrapping token is not valid or does not exist

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#217] opened 2017-12-18 21:34 UTC
Goldfish version: v0.8.0
Vault version: v0.8.3

Lately our Goldfish container (see this comment on setup https://github.com/Caiyeon/goldfish/issues/190#issuecomment-352559276) has been giving the following message after running a few hours,

```
12/1/2017 5:19:53 AMURL: PUT https://vault.ourdomain.com:8200/v1/sys/wrapping/unwrap
12/1/2017 5:19:53 AMCode: 400. Errors:
12/1/2017 5:19:53 AM
12/1/2017 5:19:53 AM* wrapping token is not valid or does not exist
12/1/2017 5:19:58 AM2017/12/01 13:19:58 [ERROR]: Bootstrapping goldfish Failed to unwrap provided token, revoke it if possible
12/1/2017 5:19:58 AMReason:Error making API request.
```

The goldfish role was setup following the guide in the wiki. The container is deployed by first getting it's wrapping token from vault with,

```
export GOLDFISH_TOKEN=`vault write -f -format=json -wrap-ttl=5m auth/approle/role/goldfish/secret-id | jq -r .wrap_info.token`
```

and then bootstrapping with the command,

```
goldfish -config=/app/config.hcl -token=${GOLDFISH_TOKEN}
```

Am I setting the wrapping token incorrectly? Or is there a way to find out why the token keeps expiring? I don't think this is a bug necessarily and it was happening with goldfish v0.7.4, but any guidance would be appreciated.

**Comment by Caiyeon** [comment] 2017-12-18 22:11
After running for a few hours successfully? The unwrapping/bootstrap step is only performed once, during launch. Is the process/container being restarted?

How long does it take between the wrapping token generation and the bootstrapping command? If it is longer than 5 minutes, then the wrapping has expired (`-wrap-ttl=5m`)

**Comment by ecliptik** [comment] 2017-12-18 22:50
@Caiyeon I haven't gauged the exact time, but last week I would re-deploy the container and could use Goldfish successfully with it fully bootstrapped. A few hours later (it stays up for more than 5 minutes) I would get reports from devs saying they couldn't access it, and when looking in the container logs I was seeing the message above repeated over and over.

The container isn't being restarted or re-deployed (it's running in Rancher and I can see it's stack history) it just starts putting those errors in the logs.

The jenkins job the deploys the container runs the vault command to get the wrapping token

```
export GOLDFISH_TOKEN=`vault write -f -format=json -wrap-ttl=5m auth/approle/role/goldfish/secret-id | jq -r .wrap_info.token`
```

and then immediately deploys the container, all of which happens in less than a minute.

Right now my current workaround is to have the jenkins job re-deploy @daily so at least it's not completely down if it gets hung for more than a day.

Is there anything I should look at to determine that the token is setup properly? Trying to do a `vault token-lookup` doesn't yield much since I don't think you can use it for wrapping tokens.

goldfish role

```
🐳  vault read auth/approle/role/goldfish
Key                     Value
---                     -----
bind_secret_id          true
bound_cidr_list   
period                  86400
policies                [default goldfish]
secret_id_num_uses      1
secret_id_ttl           300
token_max_ttl           0
token_num_uses          0
token_ttl               0
```

goldfish policy

```
🐳  vault read sys/policy/goldfish
Key     Value
---     -----
name    goldfish
rules   # [mandatory]
# store goldfish run-time settings here
# goldfish hot-reloads from this endpoint every minute
path "secret/goldfish*" {
  capabilities = ["read", "update"]
}


# [optional]
# to enable transit encryption:
# set 'ServerTransitKey' in runtime settings
# and initialize the key: 'vault write -f transit/keys/goldfish'
# see wiki for details
path "transit/encrypt/goldfish" {
  capabilities = ["read", "update"]
}
path "transit/decrypt/goldfish" {
  capabilities = ["read", "update"]
}
```

**Comment by Caiyeon** [comment] 2017-12-18 23:39
This specific code path is only executed once per runtime, so it's impossible to output this error message after a successful bootstrap (unless the process has been restarted). If it launched properly the first time, then the token is valid, but the token cannot be reused. I would look into if the executable (goldfish) is being restarted upon possible crash. I'm not sure about how rancher takes care of service lifecycles.

Is there anything peculiar in the logs right before the first occurence of the error?

**Comment by ecliptik** [comment] 2017-12-18 23:44
@Caiyeon the logs scroll away since the message keeps coming up. I'll try to catch it before it scrolls off and if I can get more info I'll update the ticket.

From what you can tell, are the steps used to generate the wrapping token from the approle and passing to Goldfish for bootstrapping correct? It looks right from following the documentation, but what I'm doing isn't fully described and I'm wondering if I'm missing something.

**Comment by Caiyeon** [comment] 2017-12-18 23:55
If it worked at all, it is correct. Goldfish will hold on to the token, and reject new tokens with a message saying it is already bootstrapped. This is why I believe the process must have been restarted (with the same token that jenkins provided the first time, which is now unusable)

**Comment by ecliptik** [comment] 2017-12-19 01:05
The container did close, and you're correct @Caiyeon that the message above is because the token was already used and the 5m ttl expired.

The log message that was in the container when it shutdown was,

```
==> Goldfish shutdown triggered
{"time":"2017-12-19T00:23:34.947865077Z","level":"-","prefix":"echo","file":"server.go","line":"148","message":"http: Server closed"}
```

That specific line 148 in `server.go` (https://github.com/Caiyeon/goldfish/blob/26a8ff5cacd608d6956745b56a455bbfe0c683e4/server/server.go#L146-L150) is about TLS - which I have disabled in the config since this container is behind a AWS ELB which handles SSL termination.

Nothing else was logged. Is there a way to increase verbosity in the server logs to see if I can get any more information?

**Comment by Caiyeon** [comment] 2017-12-19 06:42
The `==> Goldfish shutdown triggered` only comes from catching a SIGTERM or an OS level interrupt signal, as coded in here: https://github.com/Caiyeon/goldfish/blob/aa8420741900b08835e669e1c4aa41a38262cc6e/server.go#L103-L107

Assuming the environment is linux, this means something politely asked the process to shutdown. E.g. a ctrl + c, or if the OS is running out of memory. Perhaps the container ran out of memory after being active for a few hours? Goldfish (and other misc OS programs) would inevitably grow in memory requirements in a few hours.

**Comment by ecliptik** [comment] 2017-12-19 21:39
Interesting. Looking at the historicals of the the container host and other applications running on it I don't see any containers getting OOM'd or restarted. I'll dig into the Rancher logs to see if for some reason it's being restarted (which would explain the SIGTERM). There isn't a app healthcheck setup which is usually how Rancher would cycle out a failed container, but it could be something else.

Overall the container uses very little cpu and memory, and the cluster of AWS hosts it runs on have more than enough provisioned (yay spot instances).

Container in New Relic (strangely shows more memory than Rancher):
<img width="1195" alt="screen shot 2017-12-19 at 1 32 05 pm" src="https://user-images.githubusercontent.com/1261742/34179833-55792d1a-e4c1-11e7-83ea-13bad48d7b3c.png">

Container stats on Rancher:
<img width="1400" alt="screen shot 2017-12-19 at 1 32 25 pm" src="https://user-images.githubusercontent.com/1261742/34179837-5a80f6a8-e4c1-11e7-9c32-141e87f984f0.png">

**Comment by Caiyeon** [comment] 2017-12-20 06:51
If I recall correctly, spot instances can be hibernated/stopped at a given moment's notice, right? Is it possible that the process was terminated because EC2 requested the resource back? In any case, it seems that the process was indeed shutdown at 1:25 in the graphs (memory and CPU)

I hope this helps. It seems that the issue is not goldfish, since this is expected behaviour when the process terminates, so I'm closing the issue here :)

**Closed by Caiyeon** 2017-12-20 06:51 UTC

**Comment by ecliptik** [comment] 2017-12-20 16:58
This makes complete sense now, and I'll have to re-think how we're deploying Goldfish in a container. Lately Spot Instance prices have been fluctuating much more and even though the container is rescheduled if the token is expired it won't come up properly.
