### ISSUE TITLE
Paths namedspace by slash

### ISSUE THREAD

**Issue by freman** [Caiyeon/goldfish#16] opened 2017-05-10 02:09 UTC
Hi,

We've got a bunch of policy paths namespaced by slash

![image](https://cloud.githubusercontent.com/assets/506680/25880206/5f63ddf4-3579-11e7-91a3-07cee5e34e1a.png)

These don't work, all returning 404 but any other path seems to work fine

![image](https://cloud.githubusercontent.com/assets/506680/25880215/709ec3e0-3579-11e7-8fed-48eb835bf05c.png)

(Vault version is 0.6.4 if that helps?)

**Comment by Caiyeon** [comment] 2017-05-10 02:20
Caused by this https://github.com/Caiyeon/goldfish/blob/master/server.go#L42
It's not recognizing the url as I wish it did. It's not hard to fix, but I'll need to think of the best way to fix it

**Comment by Caiyeon** [comment] 2017-05-10 04:47
Fixed in https://github.com/Caiyeon/goldfish/commit/e91937440442200dbc87988813dcbc1f9d05b29d

**Closed by Caiyeon** 2017-05-10 04:47 UTC
